import React from "react";
import earth from "./earth.jpg";

function App() {
  return (
    <div className="container">
      <header className="header">
        <h1>Breaking Biochar</h1>
      </header>
      <main className="main-content">
        <section className="section">
          <h2>Biochar</h2>
          <p>
            Breaking Biochar is an Austin Texas based company that specializes
            in the production of Biochar. We focus on converting consumer waste
            into Biochar, a carbon-rich material that can be used to improve
            soil health, increase crop yields, and sequester carbon dioxide from
            the atmosphere. Our mission is to help combat climate change by
            providing an affordable and sustainable solution for carbon capture
            and storage. Ever gotten an Amazon delivery box and wish you dind't
            have to deal with it after you get your goodie delivered?. We can
            make Biochar from all of that waste and put it back into soils and
            green building materials. We are the future, and we are here now.
          </p>
          <h2>Approach</h2>
          <p>
            Biochar hacks the carbon cycle, turning waste into a resource. We
            handle the "Storage" part of Carbon Capture and Storage. Biochar
            lets the trees and plants do the "Carbon Capture" for us! Biochar is
            generated by heating organic matter in a low-oxygen environment, a
            process known as pyrolysis. We would focus on VOLUME to start by
            diverting as much carbon waste into solid carbon as we can. We will
            source carbon from the City of Austin TX using public and private
            sources for materials. We can help reduce landfill volume and help
            clean up the wastestream locally. We will sell our carbon credits on
            Puro.Earth and other marketplaces. We would also generate products
            from the biochar generated, from soil ammendments to green building
            materials such as carbonized cement. Cement is the number one
            product used by humans on the planet and it turns out that carbon
            can make it stronger and lighter. Biochar production also has the
            incredible benefit of being able to generate green fuels packed with
            hydrogen. As we gain efficiency we will bring in more equipment to
            divert gasses from production to create green fuels and green energy
            produced on site. While we are doing all of that we would continue
            to research best practices and look into scaling our operation
            across the USA. Every town can do this and we can help them get
            started. We would also look into creating a United States biochar
            standard and creating our own marketplace for credits and green
            products.
          </p>
          <h2>Benefits</h2>
          <p>
            Carbon has thousands of industrial uses, from cement production,
            soil amendments, filtration, green building materials, carbon fiber,
            and graphene. The green economy is finally here and carbon is the
            new gold. Biochar sequesters carbon for 100 years or more. Biochar
            also reduces landfill volume and their associated methane emissions.
            Combining Biochar with soil and compost can improve soil health,
            increase crop yields, and sequester carbon dioxide from the
            atmosphere.
          </p>
          <h2>Costs</h2>
          <p>
            The cost of producing Biochar is relatively low compared to other
            carbon capture technologies. The main costs are associated with the
            collection and transportation of organic waste, the energy required
            to heat the waste, and the equipment needed to produce and store the
            Biochar. However, the benefits of Biochar, such as improved soil
            health, increased crop yields, green building materials, and carbon
            sequestration, can outweigh the costs in the long run. In addition,
            the sale of carbon credits and other products generated from Biochar
            can help offset the initial investment.
          </p>
          <h2>Competition</h2>
          <p>
            In the past 20 years we have been promised the future in terms
            reducing our carbon footprint. Yet each year global emissions are
            still increasing. We've been sold on a million high tech solutions
            that ultimately go nowhere, fast. Remember glaciers? Those were
            cool. You can spend a billion dollars to make all of the machinery
            to pull carbon directly from the air but you can let the plants do
            that part for us, and it turns out there is a ton of carbon in our
            waste stream already. Oh and we don't have to inject C02 into the
            core of the earth, cause that sounds like fun. No. Instead, we get a
            clean building material that can be used in a variety of
            applications, and it turns out that plants and soil love it too. So
            we can make a profit and save the planet at the same time. Or just
            let AI just handle everything, we can micro-manage our way out of
            the climate crisis. I mean, what could go wrong? AI is amazing, it
            is great at monitoring global emissions, but as of yet AI hasn't
            actually sequestered any carbon. In fact it uses energy, and that
            energy is usually generated by burning fossil fuels. So we are going
            to need a lot of Biochar to offset that. Breaking Biochar, we are
            the future, and we are here now.
          </p>
          <h2>About Us</h2>
          <p>
            Brian Ebel is the founder of Breaking Biochar. He is a Legacy
            LEED-AP from the US Green Building Council. LEED stands for
            Leadership in Energy & Environmental Design Accredited Professional.
            He has a BS in Environmental Science from Vermont State University
            and has been working in the field of sustainability for over 10
            years. He is passionate about finding innovative solutions to combat
            climate change and protect the environment. He has campaigned for
            the environment, cleaned up NASA & IBM sites, and has been a part of
            the green building movement since 2008.
          </p>{" "}
          <p>
            Kevin Watters is the co-founder of Breaking Biochar. He has a Master
            of Science in Technology Commercialization from University of Texas,
            and a Bachelor of Architecture from Rensselaer University. in He has
            a background in engineering and has been working in the field of
            sustainable architecture and industrial design. He is passionate
            about finding profitable, sustainable solutions to our current
            challenges. He is committed to making Biochar a viable and
            cost-effective option for consumers, businesses, and society.{" "}
          </p>
          <p>
            We both believe that Biochar has the potential to revolutionize the
            way we think about waste and carbon sequestration. We are dedicated
            to making Biochar a mainstream solution for carbon capture and
            storage. We are committed to creating a sustainable future for
            generations to come. We are Breaking Biochar.
          </p>
        </section>
        {/* Add more sections as needed */}
      </main>
      <footer className="footer">
        <p>&copy; 2024 Breaking Biochar. All rights reserved.</p>
      </footer>
    </div>
  );
}

export default App;
