import React from "react";

import logo from "./bb.png";
function App() {
  return (
    <div className="container">
      <header className="header">
        <h1>Breaking Biochar</h1>
        <img src={logo} alt="Logo" />
      </header>
      <main className="main-content">
        <section className="section">
          <h2>Biochar</h2>
          <p>
            Breaking Biochar is an Austin Texas based company that specializes
            in the production of Biochar. Our focus is on converting consumer
            waste into biochar, a carbon-rich material that enhances building
            materials, improves soil health, increases crop yields, and
            sequesters carbon dioxide from the atmosphere. Our mission is to
            help combat climate change by providing an affordable and
            sustainable solution for carbon capture and storage. We are the
            future, and we are here now.
          </p>
          <h2>Approach</h2>
          <p>
            Biochar revolutionizes the carbon cycle by transforming waste into a
            valuable resource. Ever received an Amazon delivery and wished you
            didn't have to deal with the box afterward? We can produce clean
            carbon from all of that waste and put it back into the soil and into
            green building materials, otherwise that cardboard box is going to
            end up as CO2 in our atmosphere when it breaks down. We handle the
            "Storage" part of Carbon Capture and Storage. Biochar lets the trees
            and plants do the "Carbon Capture" for us! Biochar is generated by
            heating organic matter in a low-oxygen environment, a process known
            as pyrolysis. Initially, we will focus on volume, diverting as much
            carbon waste into solid carbon as possible. We will utilize an 'Air
            Curtain' that blows air onto the top of the fire, this keeps the
            smoke from being emitted and it give oxygen to the top of the fire.
            We would use the Char-Boss by Air Burners.
            https://airburners.com/products/boss-series/charboss/ It burns
            cleaner than an open burn and is considered an acceptable biochar
            technology in the EU because it burns so cleanly. The bottom of the
            pile is designed to not allow air in, so the hot, efficient burn at
            the top of the pile heats up the entire pile. The bottom of the pile
            is not recieving oxygen because the fire above it is consuming all
            of the oxygen to maintain the fire. The heat from the fire and the
            absense of oxygen is what is required to perform pyrolysis which
            creates the char. The biochar is then sent to a conveyer and is
            quenched in water, putting it out and cooling it off. Then the
            biochar is ready for storage. The Charboss only requires the
            operation of the air curtain which is essentially a fan, and the
            conveyer which sends out the biochar. We will source carbon from the
            City of Austin TX using public and private sources for materials. We
            can help reduce landfill volume and help clean up the wastestream
            locally. We will cross promote our progress as a community. Every
            household in America generates 5 pounds of trash a day and half of
            that is organic material that could become biochar. We want it. We
            will sell our carbon credits on Puro.Earth and other marketplaces.
            We would also generate products from the biochar generated, from
            soil ammendments to green building materials such as carbonized
            cement. Cement is the number one product used by humans on the
            planet and it turns out that carbon can make it stronger and
            lighter. Biochar production also has the incredible benefit of being
            able to generate green fuels packed with hydrogen. As we gain
            efficiency we will bring in more equipment to divert gasses from
            production to create green fuels and green energy produced on site.
            While we are doing all of that we would continue to research best
            practices and look into scaling our operation across the USA. Every
            town can do this and we can help them get started. We would also
            look into creating a United States biochar standard and creating our
            own marketplace for credits and green products.
          </p>
          <h2>Benefits</h2>
          <p>
            Carbon has thousands of industrial applications, including cement
            production, soil amendments, filtration, green building materials,
            carbon fiber, and graphene. The green economy is finally here and
            carbon is the new gold. Biochar sequesters carbon for 100 years or
            more. Biochar also reduces landfill volume and their associated
            methane emissions. Combining biochar with soil and compost enhances
            soil health, boosts crop yields, and sequesters carbon dioxide from
            the atmosphere. Carbon credits can be sold on the open market,
            generating revenue for the company and helping countries to meet
            their climate goals. The need for carbon sequestration is growing as
            the effects of climate change become more severe. Biochar offers a
            sustainable and cost-effective solution for capturing and storing
            carbon dioxide. By converting waste into Biochar, we reduce source
            greenhouse gas emissions, and create a more sustainable future for
            generations to come. By converting waste into Biochar before it ends
            up in a landfill we eliminate the methane production that occurs in
            landfills. Methane is 25 times more potent than CO2 as a greenhouse
            gas. Even if landfills burn the methane, it is then converted to CO2
            and released to the atmosphere. By converting waste into Biochar we
            can sequester the carbon for 100 years or more. This is a win-win
            for the environment and the economy. We can also generate green
            fuels and green energy from the gasses produced during the pyrolysis
            process. This is a great way to reduce our dependence on fossil
            fuels and reduce our carbon footprint. Biochar is a sustainable and
            cost-effective solution for carbon capture and storage. By
            converting waste into Biochar we can reduce source greenhouse gas
            emissions and create a more sustainable future for generations to
            come. We are the future, and we are here now. Breaking Biochar.
          </p>
          <h2>Costs</h2>
          <p>
            The cost of producing Biochar is relatively low compared to other
            carbon capture technologies. The main costs are associated with the
            collection and transportation of organic waste, the energy required
            to heat the waste, and the equipment needed to produce and store the
            Biochar. However, the benefits of biochar—improved soil health,
            increased crop yields, green building materials, and carbon
            sequestration—can outweigh the costs in the long run. In addition,
            the sale of carbon credits and other products generated from Biochar
            can help offset the initial investment. The operation of the
            Char-Boss requires only 1.1 gallons of diesel an hour, and uses 12
            gallons of water an hour. It doesn't need to be plugged in and it is
            a mobile machine that can be used onsite incase it is more efficient
            to move the device to the material than to move the material to the
            device.
          </p>
          <h2>Competition</h2>
          <p>
            Over the past 20 years, promises have been made about reducing our
            carbon footprint, yet global emissions continue to rise. Clean Coal,
            Bioenergy with Carbon Capture and Storage, Direct Air Capture, and
            other technologies have been proposed as solutions to the climate
            crisis. However, these technologies are expensive, unproven, and
            have limited scalability. Biochar is a cost-effective, sustainable,
            and scalable solution for carbon capture and storage. It has the
            potential to revolutionize the way we think about waste and carbon
            sequestration. We are committed to making Biochar a mainstream
            solution for carbon capture and storage. We are Breaking Biochar.
            Biochar literally only requires a fire and a barrel to produce. It
            is the most cost effective way to sequester carbon and it is the
            only way to sequester carbon in a way that is beneficial to the
            environment. The other methods of carbon capture are expensive and
            require a lot of energy to operate. Biochar is a win-win for the
            environment and the economy. We are the future, and we are here now.
            Breaking Biochar.
          </p>
          <h2>About Us</h2>
          <p>
            Brian Ebel is the founder of Breaking Biochar. He is a Legacy
            LEED-AP from the US Green Building Council. LEED stands for
            Leadership in Energy & Environmental Design Accredited Professional.
            He holds a BS in Environmental Science from Vermont State University
            and has over 10 years of experience in sustainability. He is
            passionate about finding innovative solutions to combat climate
            change and protect the environment. He has campaigned for the
            environment, cleaned up NASA & IBM sites, and been part of the green
            building movement since 2008.
          </p>{" "}
          <p>
            Kevin Watters is the co-founder of Breaking Biochar. He has a Master
            of Science in Technology Commercialization from University of Texas,
            and a Bachelor of Architecture from Rensselaer University. He has a
            background in engineering and has been working in the field of
            sustainable architecture and industrial design. He is passionate
            about finding profitable, sustainable solutions to our current
            challenges. He is committed to making Biochar a viable and
            cost-effective option for consumers, businesses, and society.{" "}
          </p>
          <p>
            We both believe that Biochar has the potential to revolutionize the
            way we think about waste and carbon sequestration. We are dedicated
            to making Biochar a mainstream solution for carbon capture and
            storage. We are committed to creating a sustainable future for
            generations to come. We are Breaking Biochar.
          </p>
          <p>
            Email us at: <a href="mailto:bcebel@gmail.com">bcebel@gmail.com</a>
            Call us at: <a href="tel:405-650-0063">405-650-0063</a>
          </p>
        </section>
        {/* Add more sections as needed */}
      </main>
      <footer className="footer">
        <p>&copy; 2024 Breaking Biochar. All rights reserved.</p>
      </footer>
    </div>
  );
}

export default App;
